name: Datadog Static Analysis

on:
  pull_request:
  push:
    branches:
      - haha

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Datadog SAST
        uses: DataDog/datadog-static-analyzer-github-action@v1
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_site: datadoghq.com
